#!/bin/bash
echo "Beginning of QA calculations of multiple AAMCC files"

# You have to change it for your system
PathToQA="/Users/rnepeiv/workINR/QA_tool/QA_tool_Hades/QA_AAMCC"
PathToQAscript="$PathToQA/FragmentationInput_mcini.C"

PathToMcini="/Users/rnepeiv/workINR/QA_tool/QA_tool_Hades/aamcc_to_mcini"
PathToConverterMcini="$PathToMcini/convertAAMCC.C"

echo "QA pdf calc START"
string4="("0", \"$PathToMcini/output\",\"$PathToMcini/input\",\"$PathToQA/output\", \"fin.root\", \"/QA_run.pdf\", $1)"
root -l << EOF
.L $PathToQAscript
FragmentationInput_mcini$string4
EOF