#!/bin/bash
string1="$1.root"
string2="$1_mcini.root"
echo "Beginning of QA calculations of " $string1 " file"

# You have to change it for your system
PathToQAtool="~/inr/QA_tool"

PathToMcini="$PathToQAtool/QA_tool/QA_tool_Hades/aamcc_to_mcini"
PathToConverterMcini="$PathToMcini/convertAAMCC.C"

echo "mcini converter START:"
string3="(\"$PathToMcini/input/$string1\",\"$PathToMcini/output/$string2\")"
root -l << EOF
.L $PathToConverterMcini
convertAAMCC$string3
EOF