#!/bin/bash
string1="$1.root"
string2="$1_mcini.root"
echo "Beginning of QA calculations of " $string1 " file"

# You have to change it for your system
PathToQAtool="~/inr/QA_tool"

PathToMcini="$PathToQAtool/QA_tool_Hades/aamcc_to_mcini"
PathToConverterMcini="$PathToMcini/convertAAMCC.C"

PathToDcmAamcc="$PathToQAtool/QA_tool_Hades/mcini_to_aamcc"
PathToConverterDcmAamcc="$PathToDcmAamcc/file_formation.cc"

PathToQA="$PathToQAtool/QA_tool_Hades/QA_AAMCC"
PathToQAscript="$PathToQA/FragmentationInput_mcini.C"

check=0
if [ $2 -eq $check ]; then
	echo "mcini converter START:"
	string3="(\"$PathToMcini/input/$string1\",\"$PathToMcini/output/$string2\")"
root -l << EOF
.L $PathToConverterMcini
convertAAMCC$string3
EOF
	echo "mcini converter END"

	echo "QA pdf calc START"
	string4="($2,\"$PathToMcini/output/$string2\",\"$PathToMcini/input/$string1\",\"$PathToQA/output\", \"/$string1\", \"/QA_$1.pdf\", $3)"
root -l << EOF
.L $PathToQAscript
FragmentationInput_mcini$string4
EOF
	echo "QA pdf calc END"
else
	echo "mcini to AAMCC converter START:"
	string3="($3,\"$PathToDcmAamcc/input\", \"$PathToDcmAamcc/output/$1Aamcc.root\")"
root -l << EOF
.L $PathToConverterDcmAamcc
file_formation$string3
EOF
	echo "mcini to AAMCC converter END"
	echo "QA pdf calc START"
	string4="($2, \"$PathToDcmAamcc/input\",\"$PathToDcmAamcc/output/$1Aamcc.root\",\"$PathToQA/output\", \"/$string1\", \"/QA_$1.pdf\", $3)"
root -l << EOF
.L $PathToQAscript
FragmentationInput_mcini$string4
EOF
	echo "QA pdf calc END"
fi

xdg-open ../QA_AAMCC/output/histos/QA_$1.pdf

